import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import "@/styles/typography.scss";
import Navbar from "@/components/layout/navbar/Navbar";
import Providers from "@/contexts/Providers";
import { ReactNode } from "react";

// 字體
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <div className="h-24"></div>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
