import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ReactNode } from "react";

import { Toaster } from "react-hot-toast";
import "./globals.css";
import Provider from "./Provider";

// Font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Provider>{children}</Provider>
        <Toaster /> {/* React hot toast */}
      </body>
    </html>
  );
}
